import Head from "next/head";
import Image from "next/image";
import Sidebar from "../components/Sidebar";
import Header from "../components/Header";

export default function Home() {
  return (
    <div className="bg-gradient-to-br from-vampire-black via-cetacean-blue-1 to-cetacean-blue-2 text-silver-chalice">
      <Head>
        <title>Messaging App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="font-work-sans">
        <Header />
        <Sidebar />
      </main>

      <footer className="flex flex-1 py-3.2 border-t-1 justify-center items-center">
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
          className="flex justify-center items-center flex-grow-1 text-sm"
        >
          Powered by{" "}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={60} height={13} />
          </span>
        </a>
      </footer>
    </div>
  );
}
